<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class SaranaPrasarana extends Model
{
    protected $table = 'sarana_prasarana';

    protected $fillable = [
        'sekolah_id',
        'tahun_ajaran',
        'perpustakaan_ada',
        'perpustakaan_kondisi',
        'laboratorium_ipa_ada',
        'laboratorium_ipa_kondisi',
        'laboratorium_bahasa_ada',
        'laboratorium_bahasa_kondisi',
        'laboratorium_komputer_ada',
        'laboratorium_komputer_kondisi',
        'ruang_keterampilan_ada',
        'ruang_keterampilan_kondisi',
        'ruang_seni_ada',
        'ruang_seni_kondisi',
        'ruang_osis_ada',
        'ruang_osis_kondisi',
        'uks_klinik_kesehatan_ada',
        'uks_klinik_kesehatan_kondisi',
        'ruang_kepala_sekolah_ada',
        'ruang_kepala_sekolah_kondisi',
        'ruang_wakil_kepala_sekolah_ada',
        'ruang_wakil_kepala_sekolah_kondisi',
        'ruang_tata_usaha_ada',
        'ruang_tata_usaha_kondisi',
        'ruang_bendahara_ada',
        'ruang_bendahara_kondisi',
        'ruang_guru_ada',
        'ruang_guru_kondisi',
        'ruang_bk_konseling_ada',
        'ruang_bk_konseling_kondisi',
        'aula_pertemuan_ada',
        'aula_pertemuan_kondisi',
        'kantin_sekolah_ada',
        'kantin_sekolah_kondisi',
        'lapangan_olahraga_ada',
        'lapangan_olahraga_kondisi',
        'lab_studio_kebaharian_ada',
        'lab_studio_kebaharian_kondisi',
        'toilet_terpisah_ada',
        'toilet_terpisah_kondisi',
        'taman_hijau_ada',
        'taman_hijau_kondisi',
        'tempat_parkir_ada',
        'tempat_parkir_kondisi',
        'ruang_ibadah_ada',
        'ruang_ibadah_kondisi',
        'ape_kb_tk_ada',
        'ape_kb_tk_kondisi',
        'ifp_dari_pemerintah_ada',
        'ifp_dari_pemerintah_kondisi',
        'laptop_ext_hd_dari_pemerintah_ada',
        'laptop_ext_hd_dari_pemerintah_kondisi',
        'luas_tanah',
        'luas_bangunan',
        'biaya_sewa_lahan',
        'jumlah_ruang_kelas',
        'kondisi_ruang_kelas',
        'memiliki_perpustakaan',
        'kondisi_perpustakaan',
        'memiliki_laboratorium',
        'jenis_laboratorium',
        'memiliki_uks',
        'kondisi_uks',
        'memiliki_lapangan',
        'kondisi_lapangan',
        'luas_bangunan_m2',
        'status_kepemilikan',
        'skor_rata_rata',
        'catatan',
        'updated_by',
    ];

    protected $casts = [
        'perpustakaan_ada' => 'boolean',
        'laboratorium_ipa_ada' => 'boolean',
        'laboratorium_bahasa_ada' => 'boolean',
        'laboratorium_komputer_ada' => 'boolean',
        'ruang_keterampilan_ada' => 'boolean',
        'ruang_seni_ada' => 'boolean',
        'ruang_osis_ada' => 'boolean',
        'uks_klinik_kesehatan_ada' => 'boolean',
        'ruang_kepala_sekolah_ada' => 'boolean',
        'ruang_wakil_kepala_sekolah_ada' => 'boolean',
        'ruang_tata_usaha_ada' => 'boolean',
        'ruang_bendahara_ada' => 'boolean',
        'ruang_guru_ada' => 'boolean',
        'ruang_bk_konseling_ada' => 'boolean',
        'aula_pertemuan_ada' => 'boolean',
        'kantin_sekolah_ada' => 'boolean',
        'lapangan_olahraga_ada' => 'boolean',
        'lab_studio_kebaharian_ada' => 'boolean',
        'toilet_terpisah_ada' => 'boolean',
        'taman_hijau_ada' => 'boolean',
        'tempat_parkir_ada' => 'boolean',
        'ruang_ibadah_ada' => 'boolean',
        'ape_kb_tk_ada' => 'boolean',
        'ifp_dari_pemerintah_ada' => 'boolean',
        'laptop_ext_hd_dari_pemerintah_ada' => 'boolean',
        'perpustakaan_kondisi' => 'integer',
        'laboratorium_ipa_kondisi' => 'integer',
        'laboratorium_bahasa_kondisi' => 'integer',
        'laboratorium_komputer_kondisi' => 'integer',
        'ruang_keterampilan_kondisi' => 'integer',
        'ruang_seni_kondisi' => 'integer',
        'ruang_osis_kondisi' => 'integer',
        'uks_klinik_kesehatan_kondisi' => 'integer',
        'ruang_kepala_sekolah_kondisi' => 'integer',
        'ruang_wakil_kepala_sekolah_kondisi' => 'integer',
        'ruang_tata_usaha_kondisi' => 'integer',
        'ruang_bendahara_kondisi' => 'integer',
        'ruang_guru_kondisi' => 'integer',
        'ruang_bk_konseling_kondisi' => 'integer',
        'aula_pertemuan_kondisi' => 'integer',
        'kantin_sekolah_kondisi' => 'integer',
        'lapangan_olahraga_kondisi' => 'integer',
        'lab_studio_kebaharian_kondisi' => 'integer',
        'toilet_terpisah_kondisi' => 'integer',
        'taman_hijau_kondisi' => 'integer',
        'tempat_parkir_kondisi' => 'integer',
        'ruang_ibadah_kondisi' => 'integer',
        'ape_kb_tk_kondisi' => 'integer',
        'ifp_dari_pemerintah_kondisi' => 'integer',
        'laptop_ext_hd_dari_pemerintah_kondisi' => 'integer',
        'luas_tanah' => 'decimal:2',
        'luas_bangunan' => 'decimal:2',
        'biaya_sewa_lahan' => 'integer',
        'memiliki_perpustakaan' => 'boolean',
        'memiliki_laboratorium' => 'boolean',
        'memiliki_uks' => 'boolean',
        'memiliki_lapangan' => 'boolean',
        'skor_rata_rata' => 'decimal:2',
        'luas_bangunan_m2' => 'decimal:2',
    ];

    public function sekolah(): BelongsTo
    {
        return $this->belongsTo(Sekolah::class, 'sekolah_id');
    }

    public function updatedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'updated_by');
    }
}
